name: Test security of python code
on:
  pull_request:
    branches:
      - main
jobs:
  bandit:
    name: Run bandit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit
      - name: Run bandit
        run: bandit $(git ls-files '*.py')
